# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
# relative_permalinks: true # ... GH-pages started failing to build !

# Setup
title:               JewelRuby
tagline:             '... bytes and babes of <span class="redish">JRuby</span>'
url:                 http://jewelruby.kares.org # http://localhost:4000
baseurl:             ''
paginate:            1
future:              false # prevent generating posts with a future date

# About/contact
author:
  name: Karol Buƒçek
  url: http://kares.org
  email: self@kares.org
  twitter: kbucek

# Defaults (posts)
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

# Custom vars
#version:             1.0.0

# Build
markdown: kramdown
highlighter: rouge
